module UIng
  # This class provides read-only access to key event properties.
  # Key events are generated by the system and should not be created or modified by the user.
  class AreaKeyEvent
    def initialize(@cstruct : LibUI::AreaKeyEvent = LibUI::AreaKeyEvent.new)
    end

    def key
      @cstruct.key
    end

    def ext_key
      @cstruct.ext_key
    end

    def modifier
      @cstruct.modifier
    end

    def modifiers
      @cstruct.modifiers
    end

    def up
      @cstruct.up
    end

    def to_unsafe
      pointerof(@cstruct)
    end
  end
end
