name: test

on:
  push:
  pull_request:
  schedule:
    - cron: "51 3 * * 6" # Runs at 03:51, only on Saturday
  workflow_dispatch:
jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu", "macos", "windows"]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: crystal-lang/install-crystal@v1
        with:
          crystal: latest
      - if: ${{ matrix.os == 'ubuntu' }}
        run: sudo apt-get install -y libgtk-3-dev
      - if: ${{ matrix.os == 'windows' }}
        name: Add Windows SDK to PATH
        run: echo "C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x64" >> $env:GITHUB_PATH
      - name: Install dependencies
        run: shards install
      - name: Run tests
        run: crystal spec
      - name: Build example
        run: |
          crystal run download.cr
          crystal build examples/control_gallery.cr
